# TypeProf 0.21.2

# Classes
module Effector
  def self.revers: -> ^(String) -> String
  def self.echoo: (Integer rate) -> ^(String) -> String
  def self.uppercase: (Integer level) -> ^(String) -> String
end

class EffectorTest
  def test_revers: -> untyped
  def test_echoo: -> untyped
  def test_uppercase: -> untyped
end
