# TypeProf 0.21.2

# Classes
class Array
  include Rainbowable
end

class String
  include Rainbowable
end

module Rainbowable
  def rainbow: -> String
end

class RainbowableTest
  def setup: -> singleton(Array)
  def test_rainbow: -> untyped
end
